export interface Language {
    en: string;
    de: string;
    description: string;
    example: string;
    example_de: string;
    formal: boolean;
    level: string;
}

export const germanEnglish: Language[] = [
    {
        en: "Hello",
        de: "Hallo",
        description: "A common greeting in English and German.",
        example: "Hello, how are you?",
        example_de: "Hallo, wie geht es dir?",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Goodbye",
        de: "Auf Wiedersehen",
        description: "A common farewell in English and German.",
        example: "Goodbye, see you later!",
        example_de: "Auf Wiedersehen, bis später!",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Please",
        de: "Bitte",
        description: "A polite way to ask for something in English and German.",
        example: "Can you help me, please?",
        example_de: "Kannst du mir bitte helfen?",
        formal: true,
        level: 'beginner',
    },
    {
        en: "Thank you",
        de: "Danke",
        description: "A way to express gratitude in English and German.",
        example: "Thank you for your help!",
        example_de: "Danke für deine Hilfe!",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Yes",
        de: "Ja",
        description: "A positive response in English and German.",
        example: "Yes, I would like that.",
        example_de: "Ja, ich möchte das.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "No",
        de: "Nein",
        description: "A negative response in English and German.",
        example: "No, thank you.",
        example_de: "Nein, danke.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Excuse me",
        de: "Entschuldigung",
        description: "A polite way to get someone's attention in English and German.",
        example: "Excuse me, can I ask you a question?",
        example_de: "Entschuldigung, darf ich Ihnen eine Frage stellen?",
        formal: true,
        level: 'beginner',
    },
    {
        en: "I'm sorry",
        de: "Es tut mir leid",
        description: "A way to express regret in English and German.",
        example: "I'm sorry for the mistake.",
        example_de: "Es tut mir leid für den Fehler.",
        formal: true,
        level: 'beginner',
    },
    {
        en: "Greetings",
        de: "Begrüßungen",
        description: "A way to say hello in English and German.",
        example: "Greetings, how are you?",
        example_de: "Begrüßungen, wie geht es dir?",
        formal: false,
        level: 'beginner',
    },
    {
        en: "How are you?",
        de: "Wie geht es dir?",
        description: "A common way to ask about someone's well-being in English and German.",
        example: "How are you doing today?",
        example_de: "Wie geht es dir heute?",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Good morning",
        de: "Guten Morgen",
        description: "A common greeting in the morning in English and German.",
        example: "Good morning, everyone!",
        example_de: "Guten Morgen, alle zusammen!",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Good night",
        de: "Gute Nacht",
        description: "A common farewell at night in English and German.",
        example: "Good night, sleep well!",
        example_de: "Gute Nacht, schlaf gut!",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Welcome",
        de: "Willkommen",
        description: "A way to greet someone who has arrived in English and German.",
        example: "Welcome to our home!",
        example_de: "Willkommen in unserem Zuhause!",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Good afternoon",
        de: "Guten Nachmittag",
        description: "A common greeting in the afternoon in English and German.",
        example: "Good afternoon, how can I help you?",
        example_de: "Guten Nachmittag, wie kann ich Ihnen helfen?",
        formal: true,
        level: 'beginner',
    },
    {
        en: "Good evening",
        de: "Guten Abend",
        description: "A common greeting in the evening in English and German.",
        example: "Good evening, it's nice to see you.",
        example_de: "Guten Abend, es ist schön, Sie zu sehen.",
        formal: true,
        level: 'beginner',
    },
    {
        en: "Hello",
        de: "Gruß Gott",
        description: "A common greeting in the southern regions of Germany.",
        example: "Gruß Gott, wie geht es Ihnen?",
        example_de: "Gruß Gott, wie geht es Ihnen?",
        formal: true,
        level: 'beginner',
    },
    {
        en: "One",
        de: "Eins",
        description: "The number ____ in English and German.",
        example: "I have one apple.",
        example_de: "Ich habe einen Apfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Two",
        de: "Zwei",
        description: "The number ____ in English and German.",
        example: "I have two apples.",
        example_de: "Ich habe zwei Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Three",
        de: "Drei",
        description: "The number three in English and German.",
        example: "I have three apples.",
        example_de: "Ich habe drei Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Four",
        de: "Vier",
        description: "The number ____ in English and German.",
        example: "I have four apples.",
        example_de: "Ich habe vier Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Five",
        de: "Fünf",
        description: "The number ____ in English and German.",
        example: "I have five apples.",
        example_de: "Ich habe fünf Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Six",
        de: "Sechs",
        description: "The number ____ in English and German.",
        example: "I have six apples.",
        example_de: "Ich habe sechs Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Seven",
        de: "Sieben",
        description: "The number ____ in English and German.",
        example: "I have seven apples.",
        example_de: "Ich habe sieben Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Eight",
        de: "Acht",
        description: "The number ____ in English and German.",
        example: "I have eight apples.",
        example_de: "Ich habe acht Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Nine",
        de: "Neun",
        description: "The number ____ in English and German.",
        example: "I have nine apples.",
        example_de: "Ich habe neun Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Ten",
        de: "Zehn",
        description: "The number ____ in English and German.",
        example: "I have ten apples.",
        example_de: "Ich habe zehn Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "How much is this?",
        de: "Wie viel kostet das?",
        description: "A way to ask for the price of something in English and German.",
        example: "How much is this shirt?",
        example_de: "Wie viel kostet dieses Hemd?",
        formal: true,
        level: 'beginner',
    },
    {
        en: "Eleven",
        de: "Elf",
        description: "The number ____ in English and German.",
        example: "I have eleven apples.",
        example_de: "Ich habe elf Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Twelve",
        de: "Zwölf",
        description: "The number ____ in English and German.",
        example: "I have twelve apples.",
        example_de: "Ich habe zwölf Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Thirteen",
        de: "Dreizehn",
        description: "The number ____ in English and German.",
        example: "I have thirteen apples.",
        example_de: "Ich habe dreizehn Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Fourteen",
        de: "Vierzehn",
        description: "The number ____ in English and German.",
        example: "I have fourteen apples.",
        example_de: "Ich habe vierzehn Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Fifteen",
        de: "Fünfzehn",
        description: "The number _____ in English and German.",
        example: "I have fifteen apples.",
        example_de: "Ich habe fünfzehn Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Sixteen",
        de: "Sechzehn",
        description: "The number _____ in English and German.",
        example: "I have sixteen apples.",
        example_de: "Ich habe sechzehn Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Seventeen",
        de: "Siebzehn",
        description: "The number _____ in English and German.",
        example: "I have seventeen apples.",
        example_de: "Ich habe siebzehn Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Eighteen",
        de: "Achtzehn",
        description: "The number _____ in English and German.",
        example: "I have eighteen apples.",
        example_de: "Ich habe achtzehn Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Nineteen",
        de: "Neunzehn",
        description: "The number _____ in English and German.",
        example: "I have nineteen apples.",
        example_de: "Ich habe neunzehn Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Twenty",
        de: "Zwanzig",
        description: "The number _____ in English and German.",
        example: "I have twenty apples.",
        example_de: "Ich habe zwanzig Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Twenty-one",
        de: "Einundzwanzig",
        description: "The number _____ in English and German.",
        example: "I have twenty-one apples.",
        example_de: "Ich habe einundzwanzig Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Twenty-two",
        de: "Zweiundzwanzig",
        description: "The number _____ in English and German.",
        example: "I have twenty-two apples.",
        example_de: "Ich habe zweiundzwanzig Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Twenty-three",
        de: "Dreiundzwanzig",
        description: "The number _____ in English and German.",
        example: "I have twenty-three apples.",
        example_de: "Ich habe dreiundzwanzig Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Twenty-four",
        de: "Vierundzwanzig",
        description: "The number _____ in English and German.",
        example: "I have twenty-four apples.",
        example_de: "Ich habe vierundzwanzig Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Twenty-five",
        de: "Fünfundzwanzig",
        description: "The number _____ in English and German.",
        example: "I have twenty-five apples.",
        example_de: "Ich habe fünfundzwanzig Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Twenty-six",
        de: "Sechsundzwanzig",
        description: "The number _____ in English and German.",
        example: "I have twenty-six apples.",
        example_de: "Ich habe sechsundzwanzig Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Twenty-seven",
        de: "Siebenundzwanzig",
        description: "The number _____ in English and German.",
        example: "I have twenty-seven apples.",
        example_de: "Ich habe siebenundzwanzig Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Twenty-eight",
        de: "Achtundzwanzig",
        description: "The number _____ in English and German.",
        example: "I have twenty-eight apples.",
        example_de: "Ich habe achtundzwanzig Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Twenty-nine",
        de: "Neunundzwanzig",
        description: "The number _____ in English and German.",
        example: "I have twenty-nine apples.",
        example_de: "Ich habe neunundzwanzig Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Thirty",
        de: "Dreißig",
        description: "The number _____ in English and German.",
        example: "I have thirty apples.",
        example_de: "Ich habe dreißig Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Thank you very much",
        de: "Vielen Dank",
        description: "A way to express deep gratitude in English and German.",
        example: "Thank you very much for your help!",
        example_de: "Vielen Dank für Ihre Hilfe!",
        formal: true,
        level: 'beginner',
    },
    {
        en: "You're welcome",
        de: "Gern geschehen",
        description: "A polite response to thank you in English and German.",
        example: "You're welcome, happy to help!",
        example_de: "Gern geschehen, ich helfe gerne!",
        formal: true,
        level: 'beginner',
    },
    {
        en: "Excuse me, where is the bathroom?",
        de: "Entschuldigung, wo ist die Toilette?",
        description: "A way to ask for the location of the bathroom in English and German.",
        example: "Excuse me, where is the bathroom?",
        example_de: "Entschuldigung, wo ist die Toilette?",
        formal: true,
        level: 'beginner',
    },
    {
        en: "Thank you very much",
        de: "Danke schön",
        description: "A way to express gratitude in English and German.",
        example: "Thank you very much for your help!",
        example_de: "Danke schön für Ihre Hilfe!",
        formal: true,
        level: 'beginner',
    },
    {
        en: "I don't understand",
        de: "Ich verstehe nicht",
        description: "A way to express confusion in English and German.",
        example: "I'm sorry, I don't understand.",
        example_de: "Es tut mir leid, ich verstehe nicht.",
        formal: true,
        level: 'beginner',
    },
    {
        en: "You are welcome",
        de: "Bitte schön",
        description: "A polite response to thank you in English and German.",
        example: "You are welcome, happy to help!",
        example_de: "Bitte schön, ich helfe gerne!",
        formal: true,
        level: 'beginner',
    },
    {
        en: "Hello",
        de: "Gruß Sie",
        description: "A formal greeting in English and German.",
        example: "Hello, how can I help you?",
        example_de: "Gruß Sie, wie kann ich Ihnen helfen?",
        formal: true,
        level: 'beginner',
    },
    {
        en: "Good day",
        de: "Guten Tag",
        description: "A formal greeting in English and German.",
        example: "Good day, how can I assist you?",
        example_de: "Guten Tag, wie kann ich Ihnen helfen?",
        formal: true,
        level: 'beginner',
    },
    {
        en: "Sometimes",
        de: "Manchmal",
        description: "A way to express frequency in English and German.",
        example: "I sometimes go to the gym.",
        example_de: "Ich gehe manchmal ins Fitnessstudio.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Always",
        de: "Immer",
        description: "A way to express frequency in English and German.",
        example: "I always drink coffee in the morning.",
        example_de: "Ich trinke immer Kaffee am Morgen.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Never",
        de: "Nie",
        description: "A way to express frequency in English and German.",
        example: "I never eat fast food.",
        example_de: "Ich esse nie Fast Food.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Today",
        de: "Heute",
        description: "A way to express time in English and German.",
        example: "Today is a beautiful day.",
        example_de: "Heute ist ein schöner Tag.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Tomorrow",
        de: "Morgen",
        description: "A way to express time in English and German.",
        example: "Tomorrow is my birthday.",
        example_de: "Morgen ist mein Geburtstag.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Yesterday",
        de: "Gestern",
        description: "A way to express time in English and German.",
        example: "Yesterday was a long day.",
        example_de: "Gestern war ein langer Tag.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Now",
        de: "Jetzt",
        description: "A way to express time in English and German.",
        example: "I am busy now.",
        example_de: "Ich bin jetzt beschäftigt.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Everything",
        de: "Alles",
        description: "A way to express totality in English and German.",
        example: "Everything is going well.",
        example_de: "Alles läuft gut.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Nothing",
        de: "Nichts",
        description: "A way to express absence in English and German.",
        example: "Nothing is wrong.",
        example_de: "Nichts ist falsch.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Something",
        de: "Etwas",
        description: "A way to express an unspecified thing in English and German.",
        example: "I need something to eat.",
        example_de: "Ich brauche etwas zu essen.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "That is all",
        de: "Das ist alles",
        description: "A way to say completion",
        example: "That is all, thank you",
        example_de: "Das is alles, danke schon",
        formal: true,
        level: "beginner",
    },
    {
        en: "I love you",
        de: "Ich liebe dich",
        description: "A way to express affection in English and German.",
        example: "I love you very much.",
        example_de: "Ich liebe dich sehr.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Coffee",
        de: "Kaffee",
        description: "A popular beverage in English and German.",
        example: "I drink coffee every morning.",
        example_de: "Ich trinke jeden Morgen Kaffee.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Tea",
        de: "Tee",
        description: "A popular beverage in English and German.",
        example: "I drink tea every evening.",
        example_de: "Ich trinke jeden Abend Tee.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Water",
        de: "Wasser",
        description: "A common drink in English and German.",
        example: "I drink water every day.",
        example_de: "Ich trinke jeden Tag Wasser.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Juice",
        de: "Saft",
        description: "A common drink in English and German.",
        example: "I drink juice in the morning.",
        example_de: "Ich trinke morgens Saft.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Beer",
        de: "Bier",
        description: "A popular beverage in English and German.",
        example: "I drink beer on weekends.",
        example_de: "Ich trinke am Wochenende Bier.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Wine",
        de: "Wein",
        description: "A popular beverage in English and German.",
        example: "I drink wine with dinner.",
        example_de: "Ich trinke Wein zum Abendessen.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Milk",
        de: "Milch",
        description: "A common drink in English and German.",
        example: "I drink milk with breakfast.",
        example_de: "Ich trinke Milch zum Frühstück.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Soda",
        de: "Limonade",
        description: "A common drink in English and German.",
        example: "I drink soda at parties.",
        example_de: "Ich trinke Limonade auf Partys.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Beverage",
        de: "Getränk",
        description: "A general term for beverages in English and German.",
        example: "I like to try new beverages.",
        example_de: "Ich probiere gerne neue Getränke.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Food",
        de: "Essen",
        description: "A general term for meals in English and German.",
        example: "I love to eat good food.",
        example_de: "Ich liebe es, gutes Essen zu essen.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Breakfast",
        de: "Frühstück",
        description: "The first meal of the day in English and German.",
        example: "I eat breakfast every morning.",
        example_de: "Ich esse jeden Morgen Frühstück.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Lunch",
        de: "Mittagessen",
        description: "The meal in the middle of the day in English and German.",
        example: "I eat lunch at noon.",
        example_de: "Ich esse um 12 Uhr Mittagessen.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Dinner",
        de: "Abendessen",
        description: "The last meal of the day in English and German.",
        example: "I eat dinner in the evening.",
        example_de: "Ich esse abends Abendessen.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Snack",
        de: "Snack",
        description: "A small meal or food item in English and German.",
        example: "I like to eat a snack in the afternoon.",
        example_de: "Ich esse gerne einen Snack am Nachmittag.",
        formal: false,
        level: 'beginner',
    },
    {
        en: 'The food is good',
        de: 'Das Essen ist gut',
        description: 'A way to express enjoyment of food in English and German.',
        example: 'The food is good here.',
        example_de: 'Das Essen ist hier gut.',
        formal: false,
        level: 'beginner',
    },
    {
        en: 'The food is bad',
        de: 'Das Essen ist schlecht',
        description: 'A way to express dislike of food in English and German.',
        example: 'The food is bad here.',
        example_de: 'Das Essen ist hier schlecht.',
        formal: false,
        level: 'beginner',
    },
    {
        en: 'The food is delicious',
        de: 'Das Essen ist köstlich',
        description: 'A way to express enjoyment of food in English and German.',
        example: 'The food is delicious here.',
        example_de: 'Das Essen ist hier köstlich.',
        formal: false,
        level: 'beginner',
    },
    {
        en: 'The car',
        de: 'Das Auto',
        description: 'A common mode of transportation in English and German.',
        example: 'The car is parked outside.',
        example_de: 'Das Auto ist draußen geparkt.',
        formal: false,
        level: 'beginner',
    },
    {
        en: "This is my car",
        de: "Das ist mein Auto",
        description: "A way to express ownership in English and German.",
        example: "This is my car.",
        example_de: "Das ist mein Auto.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "This is my house",
        de: "Das ist mein Haus",
        description: "A way to express ownership in English and German.",
        example: "This is my house.",
        example_de: "Das ist mein Haus.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "This is my job",
        de: "Das ist mein Job",
        description: "A way to express ownership in English and German.",
        example: "This is my job.",
        example_de: "Das ist mein Job.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Brother",
        de: "Bruder",
        description: "This is a family member in English and German.",
        example: "My brother is very tall.",
        example_de: "Mein Bruder ist sehr groß.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Sister",
        de: "Schwester",
        description: "This is a family member in English and German.",
        example: "My sister is very smart.",
        example_de: "Meine Schwester ist sehr klug.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Father",
        de: "Vater",
        description: "This is a family member in English and German.",
        example: "My father is a doctor.",
        example_de: "Mein Vater ist Arzt.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Mother",
        de: "Mutter",
        description: "This is a family member in English and German.",
        example: "My mother is a teacher.",
        example_de: "Meine Mutter ist Lehrerin.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Son",
        de: "Sohn",
        description: "This is a family member in English and German.",
        example: "My son is very active.",
        example_de: "Mein Sohn ist sehr aktiv.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Daughter",
        de: "Tochter",
        description: "This is a family member in English and German.",
        example: "My daughter is very talented.",
        example_de: "Meine Tochter ist sehr talentiert.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Family",
        de: "Familie",
        description: "This is a group of related people in English and German.",
        example: "My family is very important to me.",
        example_de: "Meine Familie ist mir sehr wichtig.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Friend",
        de: "Freund",
        description: "This is a person you like in English and German.",
        example: "My friend is very funny.",
        example_de: "Mein Freund ist sehr lustig.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Husband",
        de: "Mann",
        description: "This is a family member in English and German.",
        example: "My husband is very supportive.",
        example_de: "Mein Mann ist sehr unterstützend.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Wife",
        de: "Frau",
        description: "This is a family member in English and German.",
        example: "My wife is very caring.",
        example_de: "Meine Frau ist sehr fürsorglich.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Grandfather",
        de: "Großvater",
        description: "This is a family member in English and German.",
        example: "My grandfather is very wise.",
        example_de: "Mein Großvater ist sehr weise.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Grandmother",
        de: "Großmutter",
        description: "This is a family member in English and German.",
        example: "My grandmother is very kind.",
        example_de: "Meine Großmutter ist sehr nett.",
        formal: false,
        level: 'beginner',
    },
    {
        de: "Rechnung",
        en: "Bill",
        description: "A statement of money owed for goods or services in English and German.",
        example: "Can I have the bill, please?",
        example_de: "Kann ich bitte die Rechnung haben?",
        formal: true,
        level: 'beginner',
    },
    {
        de: "Tisch",
        en: "Table",
        description: "A piece of furniture with a flat top and legs in English and German.",
        example: "The table is made of wood.",
        example_de: "Der Tisch ist aus Holz.",
        formal: false,
        level: 'beginner',
    },
    {
        de: "Stuhl",
        en: "Chair",
        description: "A piece of furniture for sitting in English and German.",
        example: "The chair is very comfortable.",
        example_de: "Der Stuhl ist sehr bequem.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "thirty-one",
        de: "Einunddreißig",
        description: "The number _____ in English and German.",
        example: "I have thirty-one apples.",
        example_de: "Ich habe einunddreißig Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "thirty-two",
        de: "Zweiunddreißig",
        description: "The number ____ in English and German.",
        example: "I have thirty-two apples.",
        example_de: "Ich habe zweiunddreißig Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "thirty-three",
        de: "Dreiunddreißig",
        description: "The number ____ in English and German.",
        example: "I have thirty-three apples.",
        example_de: "Ich habe dreiunddreißig Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "thirty-four",
        de: "Vierunddreißig",
        description: "The number ____ in English and German.",
        example: "I have thirty-four apples.",
        example_de: "Ich habe vierunddreißig Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "forty",
        de: "Vierzig",
        description: "The number ____ in English and German.",
        example: "I have forty apples.",
        example_de: "Ich habe vierzig Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "forty-one",
        de: "Einundvierzig",
        description: "The number ____ in English and German.",
        example: "I have forty-one apples.",
        example_de: "Ich habe einundvierzig Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "forty-two",
        de: "Zweiundvierzig",
        description: "The number ____ in English and German.",
        example: "I have forty-two apples.",
        example_de: "Ich habe zweiundvierzig Äpfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Once again",
        de: "noch einmal",
        description: "A way to express repetition in English and German.",
        example: "Can you say that once again?",
        example_de: "Kannst du das noch einmal sagen?",
        formal: true,
        level: 'beginner',
    },
    {
        en: "I am learning German",
        de: "Ich lerne Deutsch",
        description: "A way to express language learning in English and German.",
        example: "I am learning German for my job.",
        example_de: "Ich lerne Deutsch für meinen Job.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "I am learning English",
        de: "Ich lerne Englisch",
        description: "A way to express language learning in English and German.",
        example: "I am learning English for my job.",
        example_de: "Ich lerne Englisch für meinen Job.",
        formal: false,
        level: 'beginner',
    },
    {
        en: 'forty-three',
        de: 'Dreiundvierzig',
        description: 'The number ____ in English and German.',
        example: 'I have forty-three apples.',
        example_de: 'Ich habe dreiundvierzig Äpfel.',
        formal: false,
        level: 'beginner',
    },
    {
        en: 'forty-six',
        de: 'Sechsundvierzig',
        description: 'The number ____ in English and German.',
        example: 'I have forty-six apples.',
        example_de: 'Ich habe sechsundvierzig Äpfel.',
        formal: false,
        level: 'beginner',
    },
    {
        en: 'forty-seven',
        de: 'Siebenundvierzig',
        description: 'The number ____ in English and German.',
        example: 'I have forty-seven apples.',
        example_de: 'Ich habe siebenundvierzig Äpfel.',
        formal: false,
        level: 'beginner',
    },
    {
        en: 'forty-eight',
        de: 'Achtundvierzig',
        description: 'The number ____ in English and German.',
        example: 'I have forty-eight apples.',
        example_de: 'Ich habe achtundvierzig Äpfel.',
        formal: false,
        level: 'beginner',
    },
    {
        en: 'forty-nine',
        de: 'Neunundvierzig',
        description: 'The number ____ in English and German.',
        example: 'I have forty-nine apples.',
        example_de: 'Ich habe neunundvierzig Äpfel.',
        formal: false,
        level: 'beginner',
    },
    {
        en: 'fifty',
        de: 'Fünfzig',
        description: 'The number ____ in English and German.',
        example: 'I have fifty apples.',
        example_de: 'Ich habe fünfzig Äpfel.',
        formal: false,
        level: 'beginner',
    },
    {
        en: 'fifty-one',
        de: 'Einundfünfzig',
        description: 'The number ____ in English and German.',
        example: 'I have fifty-one apples.',
        example_de: 'Ich habe einundfünfzig Äpfel.',
        formal: false,
        level: 'beginner',
    },
    {
        en: 'fifty-two',
        de: 'Zweiundfünfzig',
        description: 'The number ____ in English and German.',
        example: 'I have fifty-two apples.',
        example_de: 'Ich habe zweiundfünfzig Äpfel.',
        formal: false,
        level: 'beginner',
    },
    {
        en: 'fifty-three',
        de: 'Dreiundfünfzig',
        description: 'The number ____ in English and German.',
        example: 'I have fifty-three apples.',
        example_de: 'Ich habe dreiundfünfzig Äpfel.',
        formal: false,
        level: 'beginner',
    },
    {
        en: 'fifty-four',
        de: 'Vierundfünfzig',
        description: 'The number ____ in English and German.',
        example: 'I have fifty-four apples.',
        example_de: 'Ich habe vierundfünfzig Äpfel.',
        formal: false,
        level: 'beginner',
    },
    {
        en: 'fifty-five',
        de: 'Fünfundfünfzig',
        description: 'The number ____ in English and German.',
        example: 'I have fifty-five apples.',
        example_de: 'Ich habe fünfundfünfzig Äpfel.',
        formal: false,
        level: 'beginner',
    },
    {
        en: "Sixty",
        de: "Sechzig",
        description: 'The number ____ in English and German.',
        example: 'I have sixty apples.',
        example_de: 'Ich habe sechzig Äpfel.',
        formal: false,
        level: 'beginner',
    },
    {
        en: "Seventy",
        de: "Siebzig",
        description: 'The number ____ in English and German.',
        example: 'I have seventy apples.',
        example_de: 'Ich habe Siebzig Äpfel.',
        formal: false,
        level: 'beginner',
    },
    {
        en: "Eighty",
        de: "Achtzig",
        description: 'The number ____ in English and German.',
        example: 'I have eighty apples.',
        example_de: 'Ich habe achtzig Äpfel.',
        formal: false,
        level: 'beginner',
    },
    {
        en: "Ninety",
        de: "Neunzig",
        description: 'The number ____ in English and German.',
        example: 'I have ninety apples.',
        example_de: 'Ich habe neunzig Äpfel.',
        formal: false,
        level: 'beginner',
    },
    {
        en: "One hundred",
        de: "Einhundert",
        description: 'The number ____ in English and German.',
        example: 'I have one hundred apples.',
        example_de: 'Ich habe einhundert Äpfel.',
        formal: false,
        level: 'beginner',
    },
    {
        en: "Hundred",
        de: "Hundert",
        description: 'The number ____ in English and German.',
        example: 'I have a hundred apples.',
        example_de: 'Ich habe hundert Äpfel.',
        formal: false,
        level: 'beginner',
    },
    {
        en: 'How old are you?',
        de: 'Wie alt sind Sie?',
        description: 'A way to ask someone their age in English and German.',
        example: 'How old are you?',
        example_de: 'Wie alt sind Sie?',
        formal: true,
        level: 'beginner',
    },
    {
        en: 'How old are you?',
        de: 'Wie alt bist du?',
        description: 'A way to ask someone their age in English and German.',
        example: 'How old are you?',
        example_de: 'Wie alt bist du?',
        formal: false,
        level: 'beginner',
    },
    {
        en: 'I am twenty-six years old',
        de: 'Ich bin sechsundzwanzig Jahre alt',
        description: 'A way to express age in English and German.',
        example: 'I am twenty-six years old.',
        example_de: 'Ich bin sechsundzwanzig Jahre alt.',
        formal: true,
        level: 'beginner',
    },
    {
        en: "You",
        de: "Du",
        description: "A way to refer to someone in English and German.",
        example: "You are very kind.",
        example_de: "Du bist sehr nett.",
        formal: false,
        level: 'beginner',
    },
    {
        en: 'I',
        de: 'Ich',
        description: 'The first-person singular pronoun in English and German.',
        example: 'I am learning German.',
        example_de: 'Ich lerne Deutsch.',
        formal: false,
        level: 'beginner',
    }, {
        en: 'Bread',
        de: 'Brot',
        description: 'A staple food made from flour and water in English and German.',
        example: 'I eat bread for breakfast.',
        example_de: 'Ich esse Brot zum Frühstück.',
        formal: false,
        level: 'beginner'
    }, {
        en: 'With',
        de: 'Mit',
        description: 'A word used to indicate inclusion or accompaniment in English and German.',
        example: 'I will go with you.',
        example_de: 'Ich werde mit dir gehen.',
        formal: false,
        level: 'beginner'
    },
    {
        en: 'Nice',
        de: 'nett',
        description: 'A way to express approval or admiration in English and German.',
        example: 'That is a nice car.',
        example_de: 'Das ist ein nett Auto.',
        formal: false,
        level: 'beginner',
    },
    {
        en: 'Very tall',
        de: 'Sehr groß',
        description: 'A way to describe someone or something with great height in English and German.',
        example: 'The building is very tall.',
        example_de: 'Das Gebäude ist sehr groß.',
        formal: false,
        level: 'beginner',
    },
    {
        en: 'Smart',
        de: 'Klug',
        description: 'A way to describe someone who is intelligent in English and German.',
        example: 'She is very smart.',
        example_de: 'Sie ist sehr klug.',
        formal: false,
        level: 'beginner',
    },
    {
        en: 'Kind',
        de: 'Nett',
        description: 'A way to describe someone who is nice in English and German.',
        example: 'He is very kind.',
        example_de: 'Er ist sehr nett.',
        formal: false,
        level: 'beginner',
    },
    {
        de: 'Wie geht\'s?',
        en: 'How are you?',
        description: 'A way to ask someone about their well-being in English and German.',
        example: 'How are you doing today?',
        example_de: 'Wie geht\'s es Ihnen heute?',
        formal: true,
        level: 'beginner',
    },
    {
        en: 'I am fine',
        de: 'Mir geht es gut',
        description: 'A way to express well-being in English and German.',
        example: 'I am fine, thank you.',
        example_de: 'Mir geht es gut, danke.',
        formal: true,
        level: 'beginner',
    },
    {
        en: 'I am not fine',
        de: 'Mir geht es nicht gut',
        description: 'A way to express discomfort in English and German.',
        example: 'I am not fine, I have a headache.',
        example_de: 'Mir geht es nicht gut, ich habe Kopfschmerzen.',
        formal: true,
        level: 'beginner',
    },
    {
        en: "Train station",
        de: "Bahnhof",
        description: "A place where trains stop to pick up and drop off passengers in English and German.",
        example: "The train station is very busy.",
        example_de: "Der Bahnhof ist sehr beschäftigt.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Subway station",
        de: "U-Bahn-Station",
        description: "A place where subways stop to pick up and drop off passengers in English and German.",
        example: "The subway station is very crowded.",
        example_de: "Die U-Bahn-Station ist sehr überfüllt.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Bus station",
        de: "Bushaltestelle",
        description: "A place where buses stop to pick up and drop off passengers in English and German.",
        example: "The bus station is very busy.",
        example_de: "Die Bushaltestelle ist sehr beschäftigt.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Airport",
        de: "Flughafen",
        description: "A place where airplanes take off and land in English and German.",
        example: "The airport is very large.",
        example_de: "Der Flughafen ist sehr groß.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Train",
        de: "Zug",
        description: "A mode of transportation that runs on tracks in English and German.",
        example: "The train is very fast.",
        example_de: "Der Zug ist sehr schnell.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Subway",
        de: "U-Bahn",
        description: "An underground train system in English and German.",
        example: "The subway is very convenient.",
        example_de: "Die U-Bahn ist sehr praktisch.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Bus",
        de: "Bus",
        description: "A large vehicle that carries passengers in English and German.",
        example: "The bus is very crowded.",
        example_de: "Der Bus ist sehr voll.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Nearby",
        de: "In der Nähe",
        description: "A way to express proximity in English and German.",
        example: "There is a store nearby.",
        example_de: "Es gibt einen Laden in der Nähe.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Bakery",
        de: "Bäckerei",
        description: "A place where bread and pastries are made and sold in English and German.",
        example: "I bought bread at the bakery.",
        example_de: "Ich habe Brot in der Bäckerei gekauft.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Apple",
        de: "Apfel",
        description: "A common fruit in English and German.",
        example: "I eat an apple every day.",
        example_de: "Ich esse jeden Tag einen Apfel.",
        formal: false,
        level: 'beginner',
    },
    {
        en: "Banana",
        de: "Banane",
        description: "A common fruit in English and German.",
        example: "I eat a banana every day.",
        example_de: "Ich esse jeden Tag eine Banane.",
        formal: false,
        level: "beginner",
    },
    {
        en: "Couch",
        de: "Couch",
        description: "A piece of furniture for sitting in English and German.",
        example: "The couch is very comfortable.",
        example_de: "Die Couch ist sehr bequem.",
        formal: false,
        level: "beginner",
    },
    {
        en: "Germany",
        de: "Deutschland",
        description: "A country in Europe in English and German.",
        example: "Germany is a beautiful country.",
        example_de: "Deutschland ist ein schönes Land.",
        formal: false,
        level: "beginner",
    },
    {
        en: "Elephant",
        de: "Elefant",
        description: "A large mammal in English and German.",
        example: "The elephant is very big.",
        example_de: "Der Elefant ist sehr groß.",
        formal: false,
        level: "beginner",
    },
    {
        en: "Fish",
        de: "Fisch",
        description: "An aquatic animal in English and German.",
        example: "I like to eat fish.",
        example_de: "Ich esse gerne Fisch.",
        formal: false,
        level: "beginner",
    },
    {
        en: "Guitar",
        de: "Gitarre",
        description: "A musical instrument in English and German.",
        example: "I play the guitar.",
        example_de: "Ich spiele Gitarre.",
        formal: false,
        level: "beginner",
    },
    {
        en: "House",
        de: "Haus",
        description: "A building for living in English and German.",
        example: "This is my house.",
        example_de: "Das ist mein Haus.",
        formal: false,
        level: "beginner",
    },
    {
        en: "Hedgehog",
        de: "Igel",
        description: "A small spiny mammal in English and German.",
        example: "The hedgehog is very cute.",
        example_de: "Der Igel ist sehr süß.",
        formal: false,
        level: "beginner",
    },
    {
        en: "Youghurt",
        de: "Joghurt",
        description: "A dairy product in English and German.",
        example: "I eat yoghurt for breakfast.",
        example_de: "Ich esse Joghurt zum Frühstück.",
        formal: false,
        level: "beginner",
    },
    {
        en: "Love",
        de: "Liebe",
        description: "A strong feeling of affection in English and German.",
        example: "Love is important in life.",
        example_de: "Liebe ist wichtig im Leben.",
        formal: false,
        level: "beginner",
    },
    {
        en: "Man",
        de: "Mann",
        description: "An adult male in English and German.",
        example: "The man is very tall.",
        example_de: "Der Mann ist sehr groß.",
        formal: false,
        level: "beginner",
    },
    {
        en: "Nail",
        de: "Nagel",
        description: "A small metal spike in English and German.",
        example: "I need a nail to hang the picture.",
        example_de: "Ich brauche einen Nagel, um das Bild aufzuhängen.",
        formal: false,
        level: "beginner",
    },
    {
        en: "Orange",
        de: "Orange",
        description: "A citrus fruit in English and German.",
        example: "I like to eat oranges.",
        example_de: "Ich esse gerne Orangen.",
        formal: false,
        level: "beginner",
    },
    {
        en: "Penguin",
        de: "Pinguin",
        description: "A flightless bird in English and German.",
        example: "The penguin lives in cold regions.",
        example_de: "Der Pinguin lebt in kalten Regionen.",
        formal: false,
        level: "beginner",
    },
    {
        en: "Quiz",
        de: "Quiz",
        description: "A test of knowledge in English and German.",
        example: "We had a quiz in class today.",
        example_de: "Wir hatten heute ein Quiz im Unterricht.",
        formal: false,
        level: "beginner",
    },
    {
        en: "Red",
        de: "Rot",
        description: "A color in English and German.",
        example: "The apple is red.",
        example_de: "Der Apfel ist rot.",
        formal: false,
        level: "beginner",
    },
    {
        en: "Sun",
        de: "Sonne",
        description: "The star at the center of the solar system in English and German.",
        example: "The sun is shining brightly.",
        example_de: "Die Sonne scheint hell.",
        formal: false,
        level: "beginner",
    },
    {
        en: "Clock",
        de: "Uhr",
        description: "A device for telling time in English and German.",
        example: "The clock is on the wall.",
        example_de: "Die Uhr hängt an der Wand.",
        formal: false,
        level: "beginner",
    },
    {
        en: "Bird",
        de: "Vogel",
        description: "An animal with feathers and wings in English and German.",
        example: "The bird is singing.",
        example_de: "Der Vogel singt.",
        formal: false,
        level: "beginner",
    },
    {
        en: "Cloud",
        de: "Wolke",
        description: "A visible mass of condensed water vapor in English and German.",
        example: "The cloud is very dark.",
        example_de: "Die Wolke ist sehr dunkel.",
        formal: false,
        level: "beginner",
    },
    {
        en: "Xylophone",
        de: "Xylophon",
        description: "A musical instrument in English and German.",
        example: "The xylophone is a percussion instrument.",
        example_de: "Das Xylophon ist ein Schlaginstrument.",
        formal: false,
        level: "beginner",
    },
    {
        en: "Yak",
        de: "Yak",
        description: "A long-haired bovine in English and German.",
        example: "The yak lives in the mountains.",
        example_de: "Das Yak lebt in den Bergen.",
        formal: false,
        level: "beginner",
    },
    {
        en: "Zebra",
        de: "Zebra",
        description: "An animal with black and white stripes in English and German.",
        example: "The zebra is grazing in the field.",
        example_de: "Das Zebra grast auf dem Feld.",
        formal: false,
        level: "beginner",
    },
    {
        en: "Teacher",
        de: "Lehrer",
        description: "A person who teaches in English and German.",
        example: "The teacher is very kind.",
        example_de: "Der Lehrer ist sehr nett.",
        formal: false,
        level: "beginner",
    },
    {
        en: "Bear",
        de: "Bär",
        description: "A large mammal in English and German.",
        example: "The bear is very strong.",
        example_de: "Der Bär ist sehr stark.",
        formal: false,
        level: "beginner",
    },
    {
        en: "Oil",
        de: "Öl",
        description: "A liquid used for cooking or lubrication in English and German.",
        example: "I use oil for cooking.",
        example_de: "Ich benutze Öl zum Kochen.",
        formal: false,
        level: "beginner",
    },
    {
        en: "Foot",
        de: "Fuß",
        description: "A part of the body used for walking in English and German.",
        example: "I hurt my foot while running.",
        example_de: "Ich habe mir beim Laufen den Fuß verletzt.",
        formal: false,
        level: 'beginner',
    }

]